version: 2
# Tell CircleCI to use this workflow
workflows:
  version: 2
  default:
    jobs:
      - "python-3.6"
      - "build-docker-image"
     

jobs:
 
  "python-3.6":
    docker:
      - image: andersy005/pbs:latest

    environment:
      PYTHON: "3.6"
      ENV_NAME: "pbs-ci-dev"

    steps:
    
      # Get our data and merge with upstream
      - checkout

      # Restore cached files to speed things up
      - restore_cache:
          key: deps-{{ .Branch }}-3.6-{{ checksum "ci/environment-dev-3.6.yml" }}

      - run: # install and activate conda environment
          name: configure conda 
          command: ./ci/install-circle.sh
      - run:
          command: |
            source activate ${ENV_NAME}
            # pytest --junitxml=test-reports/junit.xml --cov=./

      - run:
          name: Code Coverage + Code Styling with (black, flake8, isort)
          command: |
            source activate ${ENV_NAME}

            echo "[Upload coverage]"
            # codecov

            echo "[flake8]"
            flake8 

            echo "[black]"
            black --check . 

            echo "[isort]"
            isort --recursive --check-only .
    
     
      # Cache some files for a speedup in subsequent builds
      - save_cache:
          key: deps-{{ .Branch }}-3.6-{{ checksum "ci/environment-dev-3.6.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
            - "/opt/conda/pkgs"

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports


  "build-docker-image":
    docker:
      - image: andersy005/pbs:latest

    environment:
      PYTHON: "3.6"
      ENV_NAME: "pbs-ci-dev"
      
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true 

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.09.1"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: 
          name: Install Docker Compose
          command: |
            set -x 
            VER="1.23.2"
            curl -L https://github.com/docker/compose/releases/download/$VER/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose



      - run:
          name: Check docker installation
          command: |
            docker version
            docker-compose version

      - run: # install and activate conda environment
          name: configure conda 
          command: ./ci/install-circle.sh
      - run:
          command: |
            source activate ${ENV_NAME}
            pbs-ci-compose


     

            
      
          

   
  