name: pbs-ci-dev
channels:
  - conda-forge
dependencies:
  - python=3.6
  - docker-py
  - autopep8
  - flake8
  - black
  - isort
  - pytest
  - coverage
  - pytest-cov
  - codecov
  - sphinx>=1.6
  - sphinx_rtd_theme
  - recommonmark 
  - numpydoc
  - nbsphinx
  - pandoc
  - ipykernel
  - pip:
    - sphinx_copybutton

